# Generated by Django 3.0.5 on 2022-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
